project:
  type: website

website:
  title: "Emily Ruvalcaba"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: flatly
    css: styles.css
    toc: false