project:
  type: website

website:
  title: "My Professional Portfolio"

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Dashboard
        href: dashboard.qmd
      - text: Shiny Apps
        href: shiny_apps.qmd
      - text: Shinylive
        href: shiny_live.qmd

format:
  html:
    theme: cosmo
    toc: true